sudo: required
servises:
  - docker

before_install:
  - docker build -t sokolnikov90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sokolnikov90/react-test npm test

after_success:
  - docker build -t sokolnikov90/multi-client ./client
  - docker build -t sokolnikov90/multi-nginx ./nginx
  - docker build -t sokolnikov90/multi-server ./server
  - docker build -t sokolnikov90/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push sokolnikov90/multi-client
  - docker push sokolnikov90/multi-nginx 
  - docker push sokolnikov90/multi-server
  - docker push sokolnikov90/multi-worker